### ISSUE TITLE
DaggerApplication instead of HasActivityInjector 

### ISSUE THREAD

**Issue by alouanemed** [SabagRonen/dagger-activity-test-sample#2]
I can’t have the fake activity created using this [method ](https://github.com/SabagRonen/dagger-activity-test-sample/blob/FragmentSample/app/src/androidTest/java/com/example/ronensabag/daggeractivitytestsample/MainViewTests.kt#L33)because in my case am extending DaggerApplication instead of implementing HasActivityInjector ? how can I achieve this ? thanks.

**Comment by SabagRonen** [comment]
@alouanemed The issue with extending DaggerComponent is that the activity injector variable is declared at DaggerApplication source file and its visibility is package scope. In order to overcome it, you can use the extension function to DaggerApplication that make the activityInjector field from DaggerApplication visible. You can look at the following branch, I have added the file MyAppTestHelper.kt which provides the extension function.
https://github.com/SabagRonen/dagger-activity-test-sample/tree/FragmentSampleWhenExtendsDaggerApplication
